apiVersion: v2
name: traefik
description: Traefik ingress controller with Gateway API support
version: 1.0.0
type: application

dependencies:
- name: traefik
  version: "34.3.0"
  repository: "https://traefik.github.io/charts"
